# Generated by Django 5.1.3 on 2024-11-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_cartitem_products_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
